apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-pod
  template:
    metadata:
      labels: 
        app: cart-pod
    spec:
      containers:
        - name: cart-c
          image: paulchek/multyk8project_cart:2